"""Translate selected running admission/parser/serializer AST sites to Lean.

The translator rejects edits to the complete pinned helper ASTs and the
specific statements it interprets. Its semantic primitives (`Config`,
`Fraction`, tuple/list iteration, equality and frozen dataclass access) still
require a separate CPython adequacy argument. This is not an interpreter.
"""

import ast
import sys

from e7c_joint_first_helper_sites import ROOT, checked_sites, function

OUTPUT = ROOT / "proof-packages/lean-core/E7CJointAdmissionGenerated.lean"
SOURCE = ROOT / "e7c_eecq_joint_restrict_b1.py"

LEAN = '''import E7CJointFirstHelperSelection

/-! Generated by `e7c_joint_admission_translation.py` from pinned actual
Python helper ASTs. `normalizer` denotes the actual `joint(parsed, arity=2)`
call: its internal collection is left arbitrary. The generated semantics
interprets only the normal row parse, rows serialization and equality-guard
path. CPython primitive and call adequacy remains a separate proof premise.
-/
namespace E7CJointAdmissionGenerated
open E7CEECQTwoStageAllInput
open E7CEECQTwoStageExactCodec

def parseGraph : WireGraph → Graph := toGraph
def serializeGraph : Graph → WireGraph := fromGraph
def parseRow : WireRow → Row := toRow
def serializeRow : Row → WireRow := fromRow
def parseRows (sourceRows : List WireRow) : List Row := sourceRows.map parseRow
def serializeRows (rows : List Row) : List WireRow := rows.map serializeRow

def admission (normalizer : List Row → List Row) (sourceRows : List WireRow) :
    Option (List Row) :=
  let returned := normalizer (parseRows sourceRows)
  if serializeRows returned == sourceRows then some returned else none

end E7CJointAdmissionGenerated
'''


def translated_program() -> str:
    checked_sites()  # complete normalized AST identity of all imported helpers
    source = SOURCE.read_text()
    nodes = {name: function(source, name) for name in ("admit", "rows", "_row", "_graph")}
    expected_returns = {
        "_graph": "return {'edges': list(g.edges), 'tag': g.tag}",
        "_row": "return {'atoms': [_graph(g) for g in atoms], 'coefficient': {'numerator': coefficient.numerator, 'denominator': coefficient.denominator}}",
        "rows": "return [_row(atoms, coefficient) for atoms, coefficient in value.terms]",
    }
    for name, expression in expected_returns.items():
        if ast.dump(nodes[name].body[-1], include_attributes=False) != ast.dump(
                ast.parse(expression).body[0], include_attributes=False):
            raise ValueError("unsupported serializer translation: " + name)
    body = list(ast.walk(nodes["admit"]))
    parse_calls = (
        "graph = Config(tuple(g['edges']), g['tag'])",
        "if _graph(graph) != g: raise JointRestrictionAdmission('noncanonical graph edges')",
        "parsed.append((Fraction(c['numerator'], c['denominator']), tuple(graphs)))",
    )
    for expected in parse_calls:
        parsed = ast.parse(expected).body[0]
        if len([node for node in body if isinstance(node, type(parsed))
                and ast.dump(node, include_attributes=False) == ast.dump(parsed, include_attributes=False)]) != 1:
            raise ValueError("unsupported row parser translation: " + expected)
    # checked_sites already enforces the adjacent normal-return suffix and
    # rejects a bypass or a second return from `admit`.
    return LEAN


def main() -> None:
    generated = translated_program()
    if "--write" in sys.argv[1:]:
        OUTPUT.write_text(generated)
    elif "--check" in sys.argv[1:]:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            raise SystemExit("generated Lean admission translation is stale")
    else:
        sys.stdout.write(generated)


if __name__ == "__main__":
    main()
