"""Translate the selected serializer helper expressions into the Lean grammar.

The check establishes a structural source/program correspondence for this
grammar. It does not verify CPython's expression, attribute or iteration engine.
"""
import ast
import json
from pathlib import Path

from e7c_joint_first_helper_sites import checked_sites, exact, function

ROOT = Path(__file__).resolve().parent
GENERATED = ROOT / "proof-packages/lean-core/E7CJointSerializerSourceGenerated.lean"


def quote(text):
    return json.dumps(text, ensure_ascii=False)


def expression(node, environment):
    if isinstance(node, ast.Name) and node.id in environment:
        return f"(.variable {environment[node.id]})"
    if isinstance(node, ast.Attribute):
        return f"(.attribute {expression(node.value, environment)} {quote(node.attr)})"
    if isinstance(node, ast.Dict) and all(isinstance(k, ast.Constant)
                                          and type(k.value) is str for k in node.keys):
        if len({k.value for k in node.keys}) != len(node.keys):
            raise ValueError("duplicate dictionary literal keys are outside this grammar")
        fields = [f"({quote(k.value)}, {expression(v, environment)})"
                  for k, v in zip(node.keys, node.values)]
        return "(.object [" + ", ".join(fields) + "])"
    if isinstance(node, ast.List):
        return "(.array [" + ", ".join(expression(v, environment) for v in node.elts) + "])"
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and not node.keywords:
        if node.func.id not in {"list", "_graph", "_row"}:
            raise ValueError("unsupported helper binding: " + node.func.id)
        return "(.call " + quote(node.func.id) + " [" + ", ".join(
            expression(v, environment) for v in node.args) + "])"
    if isinstance(node, ast.ListComp) and len(node.generators) == 1:
        gen = node.generators[0]
        if gen.ifs or gen.is_async:
            raise ValueError("filtered or async comprehension is outside this grammar")
        names = ([gen.target.id] if isinstance(gen.target, ast.Name) else
                 [v.id for v in gen.target.elts] if isinstance(gen.target, ast.Tuple)
                 and all(isinstance(v, ast.Name) for v in gen.target.elts) else [])
        if len(names) not in (1, 2) or len(set(names)) != len(names):
            raise ValueError("unsupported comprehension binding")
        scope = {name: i + len(names) for name, i in environment.items()}
        scope.update({name: i for i, name in enumerate(names)})
        return (f"(.comprehension {len(names)} {expression(gen.iter, environment)} "
                f"{expression(node.elt, scope)})")
    raise ValueError("unsupported serializer expression: " + ast.dump(node))


def generated_text(code=None):
    code = code if code is not None else (ROOT / "e7c_eecq_joint_restrict_b1.py").read_text()
    definitions = []
    for name, args, output in [("_graph", ["g"], "graphExpr"),
                               ("_row", ["atoms", "coefficient"], "rowExpr"),
                               ("rows", ["value"], "rowsExpr")]:
        node = function(code, name)
        if (node.decorator_list or node.returns or node.args.posonlyargs
                or node.args.kwonlyargs or node.args.defaults or node.args.vararg
                or node.args.kwarg or [a.arg for a in node.args.args] != args
                or any(a.annotation is not None for a in node.args.args)):
            raise ValueError("unsupported helper signature: " + name)
        if name == "rows":
            expected = ('if type(value) is not Joint or value.arity != 2:\n'
                        '    raise JointRestrictionAdmission("binary typed joint required")')
            if len(node.body) != 2 or not exact(node.body[0], expected):
                raise ValueError("binary native Joint guard changed")
        elif len(node.body) != 1:
            raise ValueError("helper contains an additional statement: " + name)
        if not isinstance(node.body[-1], ast.Return):
            raise ValueError("helper has no sole return: " + name)
        definitions.append(f"def {output} : Expr :=\n  " + expression(
            node.body[-1].value, {arg: i for i, arg in enumerate(args)}) + "\n")
    return ("import E7CJointSerializerSourceSyntax\n\n"
            "/- Generated by e7c_joint_serializer_source.py; check against the pinned\n"
            "source before use. The rows guard is the exact native Joint / arity-2\n"
            "guard checked by the translator; its selected evaluator is runRows. -/\n"
            "namespace E7CJointSerializerSourceGenerated\n"
            "open E7CJointSerializerSourceSyntax\n\n" + "\n".join(definitions) +
            "\nend E7CJointSerializerSourceGenerated\n")


def check():
    checked_sites()
    if GENERATED.read_text() != generated_text():
        raise ValueError("serializer Lean source tree differs from the pinned Python helpers")


def interpret_helper(name, *args, code=None, read_attribute=getattr, bindings=None):
    """Independent selected AST interpreter for differential evidence only.

    Python supplies native attributes and scalar/container primitives here;
    agreement in finite tests is not a proof of their general adequacy.
    """
    from eec_q_fg3_joint_b1 import Joint
    from e7c_eecq_joint_restrict_b1 import JointRestrictionAdmission

    code = code if code is not None else (ROOT / "e7c_eecq_joint_restrict_b1.py").read_text()
    generated_text(code)  # reject statements outside the complete selected grammar
    bindings = bindings or {}

    def evaluate(node, scope):
        if isinstance(node, ast.Name):
            return scope[node.id]
        if isinstance(node, ast.Attribute):
            return read_attribute(evaluate(node.value, scope), node.attr)
        if isinstance(node, ast.Dict):
            return {key.value: evaluate(value, scope)
                    for key, value in zip(node.keys, node.values)}
        if isinstance(node, ast.List):
            return [evaluate(value, scope) for value in node.elts]
        if isinstance(node, ast.Call):
            values = [evaluate(value, scope) for value in node.args]
            if node.func.id in bindings:
                return bindings[node.func.id](*values)
            if node.func.id == "list":
                return list(*values)
            return execute(node.func.id, values)
        if isinstance(node, ast.ListComp):
            gen = node.generators[0]
            output = []
            for item in evaluate(gen.iter, scope):
                local = dict(scope)
                if isinstance(gen.target, ast.Name):
                    local[gen.target.id] = item
                else:
                    values = tuple(item)
                    if len(values) != len(gen.target.elts):
                        raise ValueError("wrong tuple-unpack arity")
                    local.update((var.id, value) for var, value in zip(gen.target.elts, values))
                output.append(evaluate(node.elt, local))
            return output
        raise ValueError("unrecognized selected expression")

    def execute(helper, values):
        node = function(code, helper)
        if len(values) != len(node.args.args):
            raise ValueError("wrong helper arity")
        scope = {var.arg: value for var, value in zip(node.args.args, values)}
        if helper == "rows":
            value = scope["value"]
            if type(value) is not Joint or read_attribute(value, "arity") != 2:
                raise JointRestrictionAdmission("binary typed joint required")
        return evaluate(node.body[-1].value, scope)

    return execute(name, args)


if __name__ == "__main__":
    check()
    print("Pinned serializer helper trees match the generated Lean source expressions")
