import E7CJointSerializerObservedCertificate

namespace E7CJointSerializerObservedFixtures
open E7CEECQTwoStageExactCodec E7CJointRawJsonAdmission
open E7CJointSerializerObservedCertificate

def rows0 : List WireRow := []
def output0 : RawJson := .array []
def ledger0 : FrameLedger := [("rows.call", (.array [])), ("rows.return", (.array []))]
theorem checked0 : CaptureValid rows0 output0 ledger0 := by
  constructor <;> rfl

def rows1 : List WireRow := [⟨⟨["AB"], none⟩, ⟨["AB"], none⟩, ({ num := (1), den := 2, den_nz := by decide, reduced := by decide } : Rat)⟩, ⟨⟨["BC"], some ""⟩, ⟨["BC"], some ""⟩, ({ num := (1), den := 2, den_nz := by decide, reduced := by decide } : Rat)⟩]
def output1 : RawJson := .array [(.object [("atoms", (.array [(.object [("edges", (.array [(.string "AB")])), ("tag", (.null))]), (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))]), (.object [("atoms", (.array [(.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))]), (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))])]
def ledger1 : FrameLedger := [("rows.call", (.array [(.object [("atoms", (.array [(.object [("edges", (.array [(.string "AB")])), ("tag", (.null))]), (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))]), (.object [("atoms", (.array [(.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))]), (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))])])), ("_row.call", (.object [("atoms", (.array [(.object [("edges", (.array [(.string "AB")])), ("tag", (.null))]), (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))])), ("_graph.call", (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])), ("_graph.return", (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])), ("_graph.call", (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])), ("_graph.return", (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])), ("_row.return", (.object [("atoms", (.array [(.object [("edges", (.array [(.string "AB")])), ("tag", (.null))]), (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))])), ("_row.call", (.object [("atoms", (.array [(.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))]), (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))])), ("_graph.call", (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])), ("_graph.return", (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])), ("_graph.call", (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])), ("_graph.return", (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])), ("_row.return", (.object [("atoms", (.array [(.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))]), (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))])), ("rows.return", (.array [(.object [("atoms", (.array [(.object [("edges", (.array [(.string "AB")])), ("tag", (.null))]), (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))]), (.object [("atoms", (.array [(.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))]), (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))])]))]
theorem checked1 : CaptureValid rows1 output1 ledger1 := by
  constructor <;> rfl

def rows2 : List WireRow := [⟨⟨["AB"], none⟩, ⟨["BC"], some ""⟩, ({ num := (1), den := 2, den_nz := by decide, reduced := by decide } : Rat)⟩, ⟨⟨["BC"], some ""⟩, ⟨["AB"], none⟩, ({ num := (1), den := 2, den_nz := by decide, reduced := by decide } : Rat)⟩]
def output2 : RawJson := .array [(.object [("atoms", (.array [(.object [("edges", (.array [(.string "AB")])), ("tag", (.null))]), (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))]), (.object [("atoms", (.array [(.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))]), (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))])]
def ledger2 : FrameLedger := [("rows.call", (.array [(.object [("atoms", (.array [(.object [("edges", (.array [(.string "AB")])), ("tag", (.null))]), (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))]), (.object [("atoms", (.array [(.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))]), (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))])])), ("_row.call", (.object [("atoms", (.array [(.object [("edges", (.array [(.string "AB")])), ("tag", (.null))]), (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))])), ("_graph.call", (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])), ("_graph.return", (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])), ("_graph.call", (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])), ("_graph.return", (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])), ("_row.return", (.object [("atoms", (.array [(.object [("edges", (.array [(.string "AB")])), ("tag", (.null))]), (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))])), ("_row.call", (.object [("atoms", (.array [(.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))]), (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))])), ("_graph.call", (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])), ("_graph.return", (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])), ("_graph.call", (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])), ("_graph.return", (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])), ("_row.return", (.object [("atoms", (.array [(.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))]), (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))])), ("rows.return", (.array [(.object [("atoms", (.array [(.object [("edges", (.array [(.string "AB")])), ("tag", (.null))]), (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))]), (.object [("atoms", (.array [(.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))]), (.object [("edges", (.array [(.string "AB")])), ("tag", (.null))])])), ("coefficient", (.object [("numerator", (.integer (1))), ("denominator", (.integer (2)))]))])]))]
theorem checked2 : CaptureValid rows2 output2 ledger2 := by
  constructor <;> rfl

def rows3 : List WireRow := [⟨⟨["AB", "AC", "BC"], some "Ω\n\"\\\u0001"⟩, ⟨["BC"], some ""⟩, ({ num := (-7), den := 11, den_nz := by decide, reduced := by decide } : Rat)⟩]
def output3 : RawJson := .array [(.object [("atoms", (.array [(.object [("edges", (.array [(.string "AB"), (.string "AC"), (.string "BC")])), ("tag", (.string "Ω\n\"\\\u0001"))]), (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])])), ("coefficient", (.object [("numerator", (.integer (-7))), ("denominator", (.integer (11)))]))])]
def ledger3 : FrameLedger := [("rows.call", (.array [(.object [("atoms", (.array [(.object [("edges", (.array [(.string "AB"), (.string "AC"), (.string "BC")])), ("tag", (.string "Ω\n\"\\\u0001"))]), (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])])), ("coefficient", (.object [("numerator", (.integer (-7))), ("denominator", (.integer (11)))]))])])), ("_row.call", (.object [("atoms", (.array [(.object [("edges", (.array [(.string "AB"), (.string "AC"), (.string "BC")])), ("tag", (.string "Ω\n\"\\\u0001"))]), (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])])), ("coefficient", (.object [("numerator", (.integer (-7))), ("denominator", (.integer (11)))]))])), ("_graph.call", (.object [("edges", (.array [(.string "AB"), (.string "AC"), (.string "BC")])), ("tag", (.string "Ω\n\"\\\u0001"))])), ("_graph.return", (.object [("edges", (.array [(.string "AB"), (.string "AC"), (.string "BC")])), ("tag", (.string "Ω\n\"\\\u0001"))])), ("_graph.call", (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])), ("_graph.return", (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])), ("_row.return", (.object [("atoms", (.array [(.object [("edges", (.array [(.string "AB"), (.string "AC"), (.string "BC")])), ("tag", (.string "Ω\n\"\\\u0001"))]), (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])])), ("coefficient", (.object [("numerator", (.integer (-7))), ("denominator", (.integer (11)))]))])), ("rows.return", (.array [(.object [("atoms", (.array [(.object [("edges", (.array [(.string "AB"), (.string "AC"), (.string "BC")])), ("tag", (.string "Ω\n\"\\\u0001"))]), (.object [("edges", (.array [(.string "BC")])), ("tag", (.string ""))])])), ("coefficient", (.object [("numerator", (.integer (-7))), ("denominator", (.integer (11)))]))])]))]
theorem checked3 : CaptureValid rows3 output3 ledger3 := by
  constructor <;> rfl

end E7CJointSerializerObservedFixtures
