import E7CJointFirstHelperSelection

/-! Generated by `e7c_joint_admission_translation.py` from pinned actual
Python helper ASTs. `normalizer` denotes the actual `joint(parsed, arity=2)`
call: its internal collection is left arbitrary. The generated semantics
interprets only the normal row parse, rows serialization and equality-guard
path. CPython primitive and call adequacy remains a separate proof premise.
-/
namespace E7CJointAdmissionGenerated
open E7CEECQTwoStageAllInput
open E7CEECQTwoStageExactCodec

def parseGraph : WireGraph → Graph := toGraph
def serializeGraph : Graph → WireGraph := fromGraph
def parseRow : WireRow → Row := toRow
def serializeRow : Row → WireRow := fromRow
def parseRows (sourceRows : List WireRow) : List Row := sourceRows.map parseRow
def serializeRows (rows : List Row) : List WireRow := rows.map serializeRow

def admission (normalizer : List Row → List Row) (sourceRows : List WireRow) :
    Option (List Row) :=
  let returned := normalizer (parseRows sourceRows)
  if serializeRows returned == sourceRows then some returned else none

end E7CJointAdmissionGenerated
