import E7CJointSerializerSourceSyntax

/- Generated by e7c_joint_serializer_source.py; check against the pinned
source before use. The rows guard is the exact native Joint / arity-2
guard checked by the translator; its selected evaluator is runRows. -/
namespace E7CJointSerializerSourceGenerated
open E7CJointSerializerSourceSyntax

def graphExpr : Expr :=
  (.object [("edges", (.call "list" [(.attribute (.variable 0) "edges")])), ("tag", (.attribute (.variable 0) "tag"))])

def rowExpr : Expr :=
  (.object [("atoms", (.comprehension 1 (.variable 0) (.call "_graph" [(.variable 0)]))), ("coefficient", (.object [("numerator", (.attribute (.variable 1) "numerator")), ("denominator", (.attribute (.variable 1) "denominator"))]))])

def rowsExpr : Expr :=
  (.comprehension 2 (.attribute (.variable 0) "terms") (.call "_row" [(.variable 0), (.variable 1)]))

end E7CJointSerializerSourceGenerated
