import Lake
open Lake DSL

package "e7cLeanCore" where
  version := v!"0.1.0"

lean_lib E7CS1StrictCore
lean_lib E7CS1FG3Single
lean_lib E7CS1FG3Rows
lean_lib E7CS1ExactCollect
lean_lib E7CS1FG3Codec
lean_lib E7CS1RowsCollect
lean_lib E7CS1TagRegistry
lean_lib E7CB2Sequence
lean_lib E7CB2FiniteBridge
lean_lib E7CEECQTwoStageBridge
lean_lib E7CEECQTwoStageAllInput
lean_lib E7CEECQTwoStageOperational
lean_lib E7CEECQTwoStageExactCodec
lean_lib E7CEECQTwoStageImplementationPath
lean_lib E7CMSCObstruction
lean_lib E7CMSCFiniteClosure
lean_lib E7CJointFirstCodeSkeleton
lean_lib E7CJointFirstExecutionRelation
lean_lib E7CJointFirstHelperSelection
lean_lib E7CJointAdmissionGenerated
lean_lib E7CJointAdmissionSemantics
lean_lib E7CJointAdmissionCalls

@[default_target]
lean_lib E7CLeanCore
